apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cms-labs-terminal.fullname" . }}-controller
  labels:
    {{- include "cms-labs-terminal.labels" . | nindent 4 }}
automountServiceAccountToken: true
