{{- if and .Values.networkPolicy.enabled (or (empty .Values.networkPolicy.namespaceSelector) (empty .Values.networkPolicy.podSelector)) }}
{{- fail "networkPolicy.namespaceSelector and networkPolicy.podSelector are required when networkPolicy is enabled" }}
{{- end }}
{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cms-labs-terminal.fullname" . }}
  labels:
    {{- include "cms-labs-terminal.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "cms-labs-terminal.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.namespaceSelector | nindent 12 }}
          podSelector:
            {{- toYaml .Values.networkPolicy.podSelector | nindent 12 }}
      ports:
        {{- range .Values.targets }}
        - protocol: TCP
          port: {{ .port }}
        {{- end }}
{{- end }}
