{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cms-labs-terminal.serviceAccountName" . }}
  labels:
    {{- include "cms-labs-terminal.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
